### ISSUE TITLE
[Bug]: ASTC texture decoding error. (Specified argument was out of the range of valid values. (Parameter 'length'))

### ISSUE THREAD

**Issue by DavidLeBonk** [AssetRipper/TextureDecoder#59]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

This occurred when extracting some bundles from Nier: Reincarnation.

### Which Unity version did this occur on?

Asset ripper attempted to export to 2019.4.9f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

All assets load and extraction begins, while extracting it eventually errors out with the following traceback.
```
Error Export: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
Error Export:    at AssetRipper.TextureDecoder.Astc.AstcDecoder.DecodeIntseq(ReadOnlySpan`1 input, Int32 offset, Int32 a, Int32 b, Int32 count, Boolean reverse, Span`1 _out)
Error Export:    at AssetRipper.TextureDecoder.Astc.AstcDecoder.DecodeWeights(ReadOnlySpan`1 input, BlockData& block)
Error Export:    at AssetRipper.TextureDecoder.Astc.AstcDecoder.DecodeBlock(ReadOnlySpan`1 input, Int32 blockWidth, Int32 blockHeight, Span`1 output)
Error Export:    at AssetRipper.TextureDecoder.Astc.AstcDecoder.DecodeASTC(ReadOnlySpan`1 input, Int32 width, Int32 height, Int32 blockWidth, Int32 blockHeight, Span`1 output)
Error Export:    at AssetRipper.Export.UnityProjects.Textures.TextureConverter.TryDecodeTexture(TextureFormat textureFormat, Int32 width, Int32 height, ReadOnlySpan`1 inputSpan, Span`1 outputSpan)
Error Export:    at AssetRipper.Export.UnityProjects.Textures.TextureConverter.TryConvertToBitmap(TextureFormat textureFormat, Int32 width, Int32 height, Int32 depth, Int32 imageSize, UnityVersion version, Byte[] data, DirectBitmap`2& bitmap) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureConverter.cs:line 186
Error Export:    at AssetRipper.Export.UnityProjects.Textures.TextureConverter.TryConvertToBitmap(ITexture2D texture, DirectBitmap`2& bitmap) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureConverter.cs:line 142
Error Export:    at AssetRipper.Export.UnityProjects.Textures.TextureAssetExporter.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureAssetExporter.cs:line 58
Error Export:    at AssetRipper.Export.UnityProjects.AssetExportCollection`1.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\AssetExportCollection.cs:line 20
Error Export:    at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 267
Error Export:    at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 186
Error Export:    at AssetRipper.GUI.Electron.Program.<>c.<<CreateMenu>b__7_5>d.MoveNext() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI.Electron\Program.cs:line 250
```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13449553/AssetRipper.log)

**Comment by DavidLeBonk** [comment]
For those who get this error I am aware that AssetRipper Version: 0.3.0.3 doesnt present it

**Comment by ds5678** [comment]
> For those who get this error I am aware that AssetRipper Version: 0.3.0.3 doesnt present it

The problem likely always existed. My transition from pointers to `Span<T>` simply revealed the problem.

**Comment by DavidLeBonk** [comment]
> The problem likely always existed. My transition from pointers to `Span<T>` simply revealed the problem.

Ah well thankfully for what I am doing (map porting) the older version works just fine.

**Comment by ds5678** [comment]
Accessing external memory accidentally is not "just fine," but the effects can be minor enough to not be noticeable.
